### PR TITLE
[FIX] correctly propagate openstack errors to the user service

### PR DESCRIPTION
**Pull request by nschad**
Correctly propagate openstack related errors & issues back to the user `Service`

### CODE REVIEW

**Comment by breuerfelix** [comment]
do we really want to make these errors visible to the user? arent these more internal debugging error messags?

**Comment by nschad** [comment]
> do we really want to make these errors visible to the user? arent these more internal debugging error messags?

loadbalancermachine_controller.go#L558 is definitely important. But also unsure about the rest @dergeberl what do you think

**Comment by dergeberl** [comment]
I think the impotent events are the events with openstack create errors, to also be sure to forward quota errors to the user so he can see if something is wrong. I am not sure about the get and delete openstack errors.

**Comment by dergeberl** [comment]
@breuerfelix what do you think?

**Review by breuerfelix — APPROVED** [review]

**Pull request merged**
