### PR TITLE
🏷️ Add labels to Earthfile

### PR DESCRIPTION
**Pull request by robinschneider**
Add labels org.opencontainers.image.source and org.opencontainers.image.revision to Earthfile.
This will allow renovate to find release notes for PRs.

### CODE REVIEW

**Comment by robinschneider** [comment]
Tested with `earthly +ci`
`docker image inspect ghcr.io/stackitcloud/yawol/yawol-controller:yawol-controller-0.21.3-15-g8ec7594`
```
"Labels": {
                "dev.earthly.built-by": "homebrew-earthly",
                "dev.earthly.git-sha": "e77372274b09b5e5f8a42f1b6ac264f7149c4924",
                "dev.earthly.version": "v0.7.23",
                "org.opencontainers.image.revision": "8ec7594a27a01d6c184db71cc06a5fef8ea42790",
                "org.opencontainers.image.source": "https://github.com/stackitcloud/yawol"
            }
```

**Review by Kumm-Kai — DISMISSED** [review]
Thanks 🙂 

We've decided to drop `BUILD +set-version` and it doesn't seem to be needed, but maybe someone else knows if we can really drop it.

**Comment by hown3d** [comment]
`BUILD +set-version` could be used to set the label `org.opencontainers.image.version`

**Comment by robinschneider** [comment]
> `BUILD +set-version` could be used to set the label `org.opencontainers.image.version`

Added it as well

**Review by Kumm-Kai — APPROVED** [review]

**Pull request merged**
